accordion
schalkneethling/web-accessibility pull request #28
Opened 2020-11-09 01:09 UTC by schalkneethling

Base accordion implementation based on https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

@MarcoZehe would appreciate your feedback on this. Thank you.

fix #27

2020-11-09 01:14 UTC, schalkneethling commented on accordion/index.html
> +            </div>
Is it odd for the `label` to come after the `input`? I know it is a common pattern with `radio` and `checkbox` element to do:

```
<label for="amount-option-1">
  <input id="amount-option-1" type="radio" name="amount" value="1" />
  1
</label>
```

Is that a better approach? If so, does one still need the `for` on the label or is the association implicit because it wraps the `input` element?

2020-11-09 08:12 UTC, MarcoZehe commented on accordion/index.html
> +            </div>
For one, for LTR languages, I always find it odd if the label comes after the input. It just feels unintuitive to have to first look on the right side for what I am asked for and then enter it to the left of it. I understand that RTL changes the visual order automatically, so it would probably as awkward for Arabic or Hebrew to have to look in a spot that does not follow the intuitive reading order. Especially people with cognitive disabilities could potentially struggle with this.

As for wrapping an input in a label... I am on the fence about this one. Yes, it should implicitly name the input if the input is wrapped. But there were times when this was not always working reliably in all browser/screen reader combinations. I haven't tested this lately, and it may no longer be an issue. But problems like these which have been following me around since the beginning of web accessibility times are hard to shake off.

2020-11-09 08:29 UTC, MarcoZehe requested changes

2020-11-09 08:29 UTC, MarcoZehe commented on accordion/index.html
> +        <h3 class="accordion-heading">
I believe you forgot to add the ID that you later reference in the aria-labelledby for the section element.

2020-11-09 08:29 UTC, MarcoZehe commented on accordion/index.html
> +        <section id="section001-panel" class="accordion-panel form-fields-group"
For really correct HTML, all these below input/label, all being radio buttons, should be wrapped inside a fieldset, and the legend element, which needs to be the first child of the fieldset, is what the heading above provides. We might get away with screen readers and keyboard focus still working correctly for these radio buttons, but technically, this is invalid HTML.

2020-11-09 08:29 UTC, MarcoZehe commented on accordion/index.html
> +        <h3 class="accordion-heading">
This heading also needs an ID for the below aria-labelledby.

2020-11-11 09:06 UTC, schalkneethling commented on accordion/index.html
> +        <h3 class="accordion-heading">
When I looked at the example at https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html I saw that they added the `id` to the `button` element. That is what I did here. Would it in fact be better to have it on the `h3`?

2020-11-11 09:08 UTC, schalkneethling commented on accordion/index.html
> +        <section id="section001-panel" class="accordion-panel form-fields-group"
Gotcha. Thing is, accordion panels could potentially contain different types of content so, would it work if I did something like:

```
<section id="section001-panel" class="accordion-panel form-fields-group" aria-labelledby="section001-heading">
  <fieldset>
    <legend>Choose the number of cases</legend>
    <div class="form-input-group">
      <input id="amount-option-1" type="radio" name="amount" value="1" />
      <label for="amount-option-1">1</label>
    </div>
    <div class="form-input-group">
      <input id="amount-option-2" type="radio" name="amount" value="2" />
      <label for="amount-option-2">2</label>
    </div>
  </fieldset>
</section>
```

2020-11-11 09:10 UTC, schalkneethling commented on accordion/index.html
> +        <section id="section001-panel" class="accordion-panel form-fields-group"
or, something like this instead:

```
<h3 class="accordion-heading">
  <button type="button" id="section001-heading" class="ghost" aria-expanded="true" aria-controls="section001-panel">Choose the number of cases</button>
</h3>
<section id="section001-panel" class="accordion-panel form-fields-group">
  <fieldset aria-labelledby="section001-heading">
    <div class="form-input-group">
      <input id="amount-option-1" type="radio" name="amount" value="1" />
      <label for="amount-option-1">1</label>
    </div>
    <div class="form-input-group">
      <input id="amount-option-2" type="radio" name="amount" value="2" />
      <label for="amount-option-2">2</label>
    </div>
  </fieldset>
</section>
```

2020-11-11 09:21 UTC, MarcoZehe commented on accordion/index.html
> +        <section id="section001-panel" class="accordion-panel form-fields-group"
The first one is better since it has more native semantics. So if that looks visually OK, I'd go with that.

2020-11-11 09:23 UTC, MarcoZehe commented on accordion/index.html
> +        <h3 class="accordion-heading">
No, using the button is fine.

2020-11-11 09:24 UTC, MarcoZehe commented on accordion/index.html
> +        <h3 class="accordion-heading">
Same, you can use the button as well.

2020-11-11 09:25 UTC, MarcoZehe approved these changes
This looks OK with me with the discussed changes.

2020-12-29 06:51 UTC, merged